---
name: Lint Terraform

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Terraform
        uses: actionshub/terraform-lint@2.0.1
      - name: Terraform security scan
        uses: triat/terraform-security-scan@v3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
